DROP TABLE IF EXISTS player_overview;

CREATE TABLE player_overview (
  id INTEGER PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  class TEXT NOT NULL CHECK (class IN ('warrior', 'mage', 'rogue', 'bard')),
  equipped_weapon TEXT NOT NULL CHECK (equipped_weapon IN ('sword', 'axe', 'dagger', 'staff'))
);

INSERT INTO player_overview (id, username, class, equipped_weapon) VALUES
  (1, 'ArthasMain', 'warrior', 'axe'),
  (2, 'MoonPriest', 'bard', 'sword'),
  (3, 'xCalibur', 'rogue', 'dagger'),
  (4, 'RuneTank', 'warrior', 'axe'),
  (5, 'EluneKid', 'rogue', 'dagger'),
  (6, 'GromByte', 'bard', 'sword'),
  (7, 'ShieldTotem', 'rogue', 'dagger'),
  (8, 'VoidCook', 'mage', 'staff'),
  (9, 'easily_gullible123', 'rogue', 'dagger'),
  (10, 'NightOwlKit', 'bard', 'sword'),
  (11, 'PixelPaladin', 'bard', 'sword'),
  (12, 'SoggyWizard', 'bard', 'sword'),
  (13, 'GrumpyBard', 'warrior', 'axe'),
  (14, 'TinyTitan', 'warrior', 'axe'),
  (15, 'SilentArrow', 'rogue', 'dagger'),
  (16, 'CrimsonFang', 'bard', 'sword'),
  (17, 'FrostByte99', 'warrior', 'axe'),
  (18, 'WanderingSage', 'mage', 'staff'),
  (19, 'IronCladLuna', 'mage', 'staff'),
  (20, 'MysticRogue7', 'mage', 'staff'),
  (21, 'BlazeRunner', 'bard', 'sword'),
  (22, 'ShadowMend', 'warrior', 'dagger'),
  (23, 'GoldenTusk', 'rogue', 'dagger'),
  (24, 'VelvetHex', 'warrior', 'dagger'),
  (25, 'ThunderClap22', 'rogue', 'dagger'),
  (26, 'MossyBoulder', 'bard', 'sword'),
  (27, 'EchoWisp', 'mage', 'staff'),
  (28, 'GrittyGnome', 'warrior', 'axe'),
  (29, 'AzureFalcon', 'warrior', 'axe'),
  (30, 'NoobSlayer42', 'bard', 'sword'),
  (31, 'QuietStorm', 'mage', 'staff'),
  (32, 'PebblePirate', 'warrior', 'axe'),
  (33, 'WhimsyKnight', 'bard', 'sword'),
  (34, 'ShadowStitch', 'rogue', 'dagger'),
  (35, 'PickpocketPoe', 'rogue', 'dagger'),
  (36, 'SilentBlade', 'rogue', 'dagger'),
  (37, 'ViperStrike', 'rogue', 'dagger'),
  (38, 'DaggerDancer', 'rogue', 'dagger'),
  (39, 'StealthSneak', 'rogue', 'dagger'),
  (40, 'GloomGlider', 'rogue', 'dagger'),
  (41, 'ShadowProwler', 'rogue', 'dagger'),
  (42, 'NightStalker', 'rogue', 'dagger');
